apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: view-webhook
spec:
  homepage: https://github.com/Trendyol/kubectl-view-webhook
  shortDescription: Visualize your webhook configurations
  version: {{ .TagName }}
  description: |
    Visualize critical parts of the admission webhook configuration resource
  platforms:
    - selector:
        matchExpressions:
          - key: os
            operator: In
            values:
              - darwin
              - linux
      {{addURIAndSha "https://github.com/Trendyol/kubectl-view-webhook/archive/{{ .TagName }}.tar.gz" .TagName }}
      bin: https://github.com/Trendyol/kubectl-view-webhook